describe("Prueba", function() {
    it('Testing', function() {
       cy.visit('https://www.demoblaze.com/index.html')
       cy.get('.col-lg-4:nth-child(2) > .card > .card-block > .card-title > .hrefch').click()
       cy.visit('https://www.demoblaze.com/prod.html?idp_=2')
       cy.get('.row > #tbodyid > .row > .col-sm-12 > .btn').click()
       cy.get('.container > #navbarExample > .navbar-nav > .active > .nav-link').click()
       cy.visit('https://www.demoblaze.com/index.html')
       cy.get('.col-lg-4:nth-child(1) > .card > .card-block > .card-title > .hrefch').click()
       cy.visit('https://www.demoblaze.com/prod.html?idp_=8')
       cy.get('.row > #tbodyid > .row > .col-sm-12 > .btn').click()
       cy.get('.container > #navbarExample > .navbar-nav > .nav-item > #cartur').click()
       cy.visit('https://www.demoblaze.com/cart.html')
       cy.get('body > #page-wrapper > .row > .col-lg-1 > .btn').click()
       cy.get('.modal-content > .modal-body > form > .form-group > #name').click()
       cy.get('.modal-content > .modal-body > form > .form-group > #name').type('Jorge')
       cy.get('.modal-content > .modal-body > form > .form-group > #country').click()
       cy.get('.modal-content > .modal-body > form > .form-group > #country').type('Ecuador')
       cy.get('.modal-content > .modal-body > form > .form-group > #city').click()
       cy.get('.modal-content > .modal-body > form > .form-group > #city').type('Guayaquil')
       cy.get('.modal-content > .modal-body > form > .form-group > #card').click()
       cy.get('.modal-content > .modal-body > form > .form-group > #card').type('54878120001')
       cy.get('.modal-content > .modal-body > form > .form-group > #month').click()
       cy.get('.modal-content > .modal-body > form > .form-group > #month').type('12')
       cy.get('.modal-content > .modal-body > form > .form-group > #year').click()
       cy.get('.modal-content > .modal-body > form > .form-group > #year').type('2024')
       cy.get('#orderModal > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
       cy.get('.modal-open > .sweet-alert > .sa-button-container > .sa-confirm-button-container > .confirm').click()
       cy.visit('https://www.demoblaze.com/index.html')
    })
   })
   